---
# result-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: camesa/voting-app-result:v0.1.8
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
# result-service
apiVersion: v1
kind: Service
metadata:
  name: servicio-result
spec:
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
# result-hpa
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-result
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: despliegue-result
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
