---
# vote-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: camesa/voting-app-vote:v0.1.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
# vote-service
apiVersion: v1
kind: Service
metadata:
  name: servicio-vote
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
---
# result-hpa
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-vote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: despliegue-vote
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
