---
# worker-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: camesa/worker:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
# worker-service
apiVersion: v1
kind: Service
metadata:
  name: servicio-worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# worker-hpa
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: despliegue-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
